README.md, chrome-implementation-differences.md
This creates a uniform API surface with other built-in AI APIs such as translation.
Fixes #1 by moving from "text session" to "assistant". Fixes #21 by adding AbortSignals in multiple places.
=> Overhaul the API surface

README.md
Closes #28. See also #7.
@sushraja-msft @lozy219 can you take a look?
=> Allow assistant-role prompts and multiple prompts

README.md
@domenic This is your branch rebased, as I noticed the rename change is currently missing in `main`.
=> Rename supportsLanguage() to languageAvailable()

README.md
Couple of corrections in the sample code: 
-   Using `languageModel` instead of `assistant` 
- `promptWithCalculator` uses `prompt` instead of text
=> chore: edits in code sample

README.md
Remove the `ai.languageModel.capabilities()` method and its accompanying `AILanguageModelCapabilities` class. Instead, replace it with:
* `ai.languageModel.availability(options)`, which takes the same options as `ai.languageModel.create()`, and returns the corresponding availability.
* `ai.languageModel.params()`, which returns the default and max params (currently top-K and temperature).
Additionally, add the `expectedInputLanguages` option to `create()` and `availability()`. The addition of this option to `create()` allows the web developer to signal the expected input languages ahead of time, allowing the downloading of additional material, or fast-failing if the additional material cannot be supported. The addition of this option to `availability()` replaces the `(await …
=> Overhaul availability testing and add expected input languages

README.md
It seems the return type should be `Promise<AILanguageModelParams?>` instead of `Promise<AILanguageModelInfo?>`.
=> Update the promise type of AILanguageModelFactory.params()

README.md
See https://github.com/webmachinelearning/writing-assistance-apis/issues/15.
=> Change progress to be between 0 and 1

README.md
See https://github.com/webmachinelearning/writing-assistance-apis/issues/29.
=> Update availability values and add "downloading"

README.md
This change adds support for structured outputs, JSON outputs to the prompt API, following up from issue https://github.com/webmachinelearning/prompt-api/issues/35.
We are planning to add support for structured outputs to chromium https://issues.chromium.org/issues/391919456, tracks the dev work in chromium.
=> Add structured outputs

README.md
Closes #40. Somewhat helps with #70.
=> Add image and audio prompting API

README.md
This is mostly to align with https://github.com/webmachinelearning/writing-assistance-apis/pull/43:
* Use the proposed QuotaExceededError when appropriate, instead of a "QuotaExceededError" DOMException.
* Rename maxTokens/tokensSoFar to inputQuota/inputUsage.
* Rename countPromptTokens() to measureInputUsage().
* Remove tokensLeft.
* Rename "contextoverflow" to "quotaoverflow".
=> Update token-counting and context overflow API surface

README.md
Follows https://github.com/webmachinelearning/writing-assistance-apis/pull/45.
=> Remove the "AI" namespace

README.md
As discussed in https://github.com/webmachinelearning/prompt-api/pull/89#issuecomment-2756808994, the shorthands can cause some confusion in this case.
=> Add multiple modalities in a single message; remove some shorthands

README.md
=> Add append() for appending without a response

README.md
Closes #102. As discussed there, it probably isn't necessary, the naming is potentially confusing, and it can be added back later if we want it.
FYI @clarkduvall @sushraja-msft.
=> Remove LanguageModelResponseSchema class

README.md
See discussions in https://github.com/webmachinelearning/prompt-api/issues/92#issuecomment-2811773119 onward.
@lozy219 PTAL! Also cc @clarkduvall.
=> More detail on append() aborting and other semantics

README.md
Just doing the { role: "system", content: ... } version inside initialPrompts fits better with established APIs, and avoids any potential confusion by having both systemPrompt and initialPrompts.
Closes #103. @michaelwasserman PTAL!
=> Remove systemPrompt in favor of the longhand

README.md
Closes #91.
@clarkduvall PTAL!
=> Add RegExp constraints and change structured output API

README.md
This makes it clear that "content" is always a peer to "role", whereas "value" only appears when you're using the longhand content array form which takes { type, value } pairs.
Most existing APIs instead do { type: "image", image: theValue }, { type: "text", text: theValue }, etc. This is not really appropriate for a web API, so we don't end up copying them exactly. But none of the existing APIs use "content" at both the outer and inner levels, so it's probably a good idea to avoid that path.
=> Rename innermost prompt property from "content" to "value"

README.md
The previous IDL had an invalid union of two `sequence<dictionaries>`, which are not distinguishable.
This new approach is mostly the same. However, it also allows mixtures of shorthand and non-shorthand contents, e.g. `[{ role: "user", content: "Foo" }, { role: "user", content: [{ type: "text", value: "Bar" }] }]`. That seems like a good thing.
@michaelwasserman PTAL
=> Fix IDL for prompts, again

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/prompt-api/pull/123.html" title="Last updated on Jun 5, 2025, 4:49 AM UTC (2208ec5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/prompt-api/123/e91269e...2208ec5.html" title="Last updated on Jun 5, 2025, 4:49 AM UTC (2208ec5)">Diff</a>
=> Specify prompt validation and canonicalization

README.md, index.bs
Closes #118.
(On top of #123, don't merge until that merges.)
***
<a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/prompt-api/pull/124.html" title="Last updated on Jun 13, 2025, 12:25 AM UTC (ca32e01)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/prompt-api/124/eb8768b...ca32e01.html" title="Last updated on Jun 13, 2025, 12:25 AM UTC (ca32e01)">Diff</a>
=> Add prefills (assistant prefixes)

README.md, index.bs
And note that by default, the implementation may do so.
Closes #125.
@cduvall to review.
***
<a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/prompt-api/pull/128.html" title="Last updated on Jun 13, 2025, 5:00 AM UTC (6595cf2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/prompt-api/128/66ab78e...6595cf2.html" title="Last updated on Jun 13, 2025, 5:00 AM UTC (6595cf2)">Diff</a>
=> Add control over including schemas for structured output

index.bs
Also note that we are protected from prefix appearing on messages containing image or audio content.
FYI @michaelwasserman
***
<a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/prompt-api/pull/129.html" title="Last updated on Jun 20, 2025, 5:13 AM UTC (803e7b7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/prompt-api/129/9df9109...803e7b7.html" title="Last updated on Jun 20, 2025, 5:13 AM UTC (803e7b7)">Diff</a>
=> Specify adjacent text-collapsing behavior

README.md, index.bs
This CL is from the proposal of https://github.com/webmachinelearning/prompt-api/issues/7#issuecomment-2942909973. It places the declaration of `tools `into `LanguageModelCreateCoreOptions` dictionary so as to let the tools to be declared in the system prompt.
***
<a href="https://pr-preview.s3.amazonaws.com/FrankLi-MSFT/prompt-api/pull/131.html" title="Last updated on Jun 24, 2025, 1:43 AM UTC (970233a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/prompt-api/131/ab9f257...FrankLi-MSFT:970233a.html" title="Last updated on Jun 24, 2025, 1:43 AM UTC (970233a)">Diff</a>
=> Support for tool/function calling

README.md
Resolves #126 
I was trying to use this function and ran into the same issue described above, where it was not clear that the input could be an array of messages. This doc update resolves that.
=> Update measureInputUsage() docs to include multimodal input array
